name: Build VIP Module

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - created

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    permissions:
      contents: write
    runs-on: ubuntu-22.04

    env:
      HL2SDK_ROOT: "${{ github.workspace }}/external"
      MMS_PATH: "${{ github.workspace }}/external/metamod-source"
      MANIFEST_PATH: "${{ github.workspace }}/external/metamod-source/hl2sdk-manifests"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update -qy
          sudo apt-get install -y git clang g++-multilib gcc-multilib lib32stdc++-11-dev lib32z1-dev libc6-dev-i386
          python3 -m pip install --upgrade pip importlib-metadata
          python3 -m pip install setuptools==45.2.0
          git clone https://github.com/alliedmodders/ambuild.git
          cd ambuild
          python3 -m pip install .
          cd ..
          mkdir -p external
          cd external
          git clone --recursive --branch master --single-branch https://github.com/alliedmodders/metamod-source.git
          git clone --recursive --branch cs2 --single-branch https://github.com/alliedmodders/hl2sdk.git hl2sdk-cs2
          cd ..
          
          # Clone and set up SchemaEntity
          git clone https://github.com/pisex/SchemaEntity.git
          
          # Create necessary directories and copy files
          mkdir -p VIP_Items/src/sdk
          cp -r SchemaEntity/* VIP_Items/src/sdk/
          
          # Clean up cloned repository
          rm -rf SchemaEntity

      - name: Configure and build plugin
        run: |
          # Create a build directory outside the source tree
          mkdir -p build
          cd build
          
          # Run configure from the build directory
          python3 ../VIP_Items/src/configure.py \
            --enable-optimize \
            --sdks cs2 \
            --targets x86_64 \
            --hl2sdk-manifests=$MANIFEST_PATH \
            --mms_path=$MMS_PATH \
            --hl2sdk-root=$HL2SDK_ROOT
          
          # Create a symlink to the SDK directory for includes
          ln -s ../VIP_Items/src/sdk sdk
          
          # Run ambuild
          ambuild

      - name: Create archive
        run: |
          cd build/package
          # Remove any existing zip files
          rm -f *.zip
          zip -r ${{ github.workspace }}/VIP_Items.zip addons

      - name: Upload archive to artifact
        uses: actions/upload-artifact@v4
        with:
          name: VIP_Items
          path: VIP_Items.zip

  release:
    needs: build
    if: github.event_name == 'release'
    permissions:
      contents: write
    runs-on: ubuntu-22.04
  
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: VIP_Items
          path: .
  
      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          files: VIP_Items.zip
