name: Build VIP Module

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-22.04

    env:
      HL2SDK_ROOT: "${{ github.workspace }}/external"
      MMS_PATH: "${{ github.workspace }}/external/metamod-source"
      MANIFEST_PATH: "${{ github.workspace }}/external/metamod-source/hl2sdk-manifests"
      SCHEMA_PATH: "${{ github.workspace }}/external/SchemaEntity"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo dpkg --add-architecture i386
          sudo apt-get update -qy
          sudo apt-get install -y git clang binutils python3 zip \
            gcc-multilib g++-multilib libc6-dev-i386 linux-libc-dev:i386
          python3 -m pip install --upgrade pip importlib-metadata
          python3 -m pip install setuptools==45.2.0
          
          # Install AMBuild
          git clone https://github.com/alliedmodders/ambuild.git
          cd ambuild
          pip install .
          cd ..
          
          # Setup external dependencies
          mkdir -p external
          cd external
          
          # Clone required repositories with specific branches
          git clone --recursive https://github.com/alliedmodders/metamod-source.git
          cd metamod-source
          git checkout master
          cd ..
          
          git clone --recursive https://github.com/alliedmodders/sourcemod.git
          cd sourcemod
          git checkout master
          cd ..
          
          # Clone CS2 SDK with specific branch
          git clone --recursive https://github.com/alliedmodders/hl2sdk.git hl2sdk-cs2
          cd hl2sdk-cs2
          git checkout cs2
          cd ..
          
          # Clone hl2sdk-manifests
          git clone https://github.com/alliedmodders/hl2sdk-manifests.git
          
          # Clone SchemaEntity
          git clone https://github.com/Pisex/SchemaEntity.git
          cd ..

      - name: Setup Schema Files
        run: |
          # Create schema directory in VIP_Items if it doesn't exist
          mkdir -p VIP_Items/src/SchemaEntity
          # Copy all schema files
          cp -r external/SchemaEntity/* VIP_Items/src/SchemaEntity/

      - name: Build VIP_Items
        run: |
          cd VIP_Items
          # Clean up any existing build artifacts
          rm -f VIP_Items.zip
          rm -f build/VIP_Items.zip
          rm -rf build/*
          
          mkdir -p build
          cd src
          mkdir -p build
          cd build
          
          # Configure with specific paths
          python3 ../configure.py \
            --enable-optimize \
            --symbol-files \
            --sdks cs2 \
            --hl2sdk-root=$HL2SDK_ROOT \
            --mms_path=$MMS_PATH \
            --hl2sdk-manifests=$MANIFEST_PATH
          
          ambuild

          # Verify required files and structure before zipping
          if [ -d "package/addons" ]; then
            # Check for .vdf file
            if [ ! -f "package/addons/metamod/vip_items.vdf" ]; then
              echo "Error: vip_items.vdf is missing"
              exit 1
            fi
            
            # Check for .so file
            if [ ! -f "package/addons/vip_modules/vip_items.so" ]; then
              echo "Error: vip_items.so is missing"
              exit 1
            fi
            
            # Check for config file
            if [ ! -f "package/addons/configs/vip/vip_items.ini" ]; then
              echo "Error: vip_items.ini is missing"
              exit 1
            fi
            
            echo "All required files present, creating zip..."
            
            # If all files exist, create the zip
            cd package/addons
            # Remove any existing zip before creating new one
            rm -f ../../../VIP_Items.zip
            zip -r ../../../VIP_Items.zip .
            echo "Zip file created successfully"
          else
            echo "Error: build directory structure is incorrect"
            exit 1
          fi

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: VIP_Items
          path: VIP_Items/VIP_Items.zip

      - name: Upload release
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: VIP_Items/VIP_Items.zip
